import { StyleSheet } from 'react-native';

const styles=StyleSheet.create({
    header:{
        height:90,
        paddingHorizontal:10,
        backgroundColor:'white'
    },
    body:{
        flex:1,
        backgroundColor:'#cce6ff',
    },
    title:{
        justifyContent:'center',
        alignItems:'center',
        height:35
    },
    form:{
        height:50,
        paddingHorizontal:10,
        alignItems:'center',
        flexDirection:'row',
    },
    txtTitle:{
        fontSize:22
    },
    btnForm:{
        paddingHorizontal:10,
        justifyContent:'center',
        height:40,
        backgroundColor:'#1a75ff',
        marginLeft:20,
        borderRadius:10
    },
    txtBtn:{
        fontSize:18,
        color:'white'
    },
    txtInput:{
        flex:1,
        height:40,
        borderColor:'gray',
        borderWidth:1,
        marginVertical:5,
        borderRadius:10,
        paddingHorizontal:10
    },
    imgIcon:{
        width:30,
        height:30,
    },
    containerTask:{
        height:50,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingHorizontal:15,
        backgroundColor:'white',
        marginHorizontal:10,
        marginVertical:10,
        borderRadius:10,
        elevation:2,
    },
    boxTask:{
        flex:1,
        marginHorizontal:10
    }
})

export default styles;